# A set of configuration
defaults:
 - _self_
 - module: default
 - override hydra/help: datacrumbs_help.yaml
 - override hydra/job_logging: disabled
 - override hydra/hydra_logging: disabled
hydra:
  run:
    dir: ./hydra_log/${module.name}/${now:%Y-%m-%d}-${now:%H-%M-%S}