name: default
install_dir: build
mode: trace
file: trace.pfw
user:
  - name: app
    link: /home/cc/datacrumbs/build/tests/df_tracer_test
    regex: .*
  - name: mpi
    link: /opt/spack/opt/spack/linux-ubuntu22.04-m1/gcc-11.4.0/openmpi-5.0.5-j267g7kotefkm6e5hi7veb6xzak4gozk/lib/libmpi.so
    regex: ^PMPI.*

profile:
  interval_sec: 1

trace:
  args: 1