name: default
install_dir: build
mode: trace
file: trace.pfw
user:
  - name: app
    link: /opt/ior/install/bin/ior
    regex: .*
  # - name: app2
  #   link: /home/cc/datacrumbs/build/tests/df_tracer_test
  #   regex: .*
  # - name: app3
  #   link: /opt/ior/install/bin/ior
  #   regex: .*
  - name: mpi
    link: /opt/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.4.0/openmpi-5.0.5-nhqsyp7dg7av22tbu3j4v7kyniocbitn/lib/libmpi.so
    regex: ^PMPI.*
  - name: hdf5
    link: /opt/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.4.0/hdf5-1.14.5-koneomxj35c5mjo47e5qqz7jxuiesgqo/lib/libhdf5.so
    regex: ^H5.*

profile:
  interval_sec: 0.0001

trace:
  args: 1
  type: ring_buffer # ring_buffer