name: default
install_dir: build
file: profile.pfw
user:
  - name: app
    link: /home/cc/datacrumbs/build/tests/df_tracer_test
    regex: .*
  - name: mpi
    link: /home/cc/datacrumbs/dependency/.spack-env/view/lib/libmpi.so
    regex: ^PMPI.*

profile:
  interval_sec: 1 