name: default
install_dir: build
mode: trace
file: trace-posix.pfw
user:
  - name: app1
    link: /home/cc/datacrumbs/build/tests/df_tracer_test
    regex: .*

profile:
  interval_sec: 0.0001

trace:
  args: 1
  type: ring_buffer # ring_buffer